import 'package:flutter/material.dart';

Color bgColor = const Color(0xff101012);
Color buttonColor = const Color(0xff8A98B7);

// todo------------------------------> Popular
List popularImage = [
  'assets/images/HomePage_Images/love.jpg',
  'assets/images/HomePage_Images/life.jpg',
  'assets/images/HomePage_Images/work.jpg',
  'assets/images/HomePage_Images/mom.jpg',
  'assets/images/HomePage_Images/friends.jpg',
  'assets/images/HomePage_Images/motivation.jpg',
];

List popularText = [
  'Love  ',
  'Life  ',
  'Work  ',
  'Mother  ',
  'Friendship  ',
  'Motivate  ',
];

// todo------------------------------> Motivation
List motivationImage = [
  'assets/images/HomePage_Images/Motivation_Images/inspiration.jpg',
  'assets/images/HomePage_Images/Motivation_Images/motivation.jpg',
  'assets/images/HomePage_Images/Motivation_Images/courage.jpg',
  'assets/images/HomePage_Images/Motivation_Images/freedome.jpg',
  'assets/images/HomePage_Images/Motivation_Images/intelligence.jpg',
  'assets/images/HomePage_Images/Motivation_Images/knowledge.jpg',
];

List motivationText = [
  'Inspiration  ',
  'Motivation  ',
  'Courage  ',
  'Freedom  ',
  'Intelligence  ',
  'Knowledge  ',
];

// todo------------------------------> Feelings
List feelingsImage = [
  'assets/images/HomePage_Images/Feelings_Images/alone.jpg',
  'assets/images/HomePage_Images/Feelings_Images/sad.jpg',
  'assets/images/HomePage_Images/Feelings_Images/trust.jpg',
  'assets/images/HomePage_Images/Feelings_Images/revenge.jpg',
  'assets/images/HomePage_Images/Feelings_Images/attitude.jpg',
  'assets/images/HomePage_Images/Feelings_Images/angry.jpg',
];

List feelingsText = [
  'Alone  ',
  'Sad  ',
  'Trust  ',
  'Revenge  ',
  'Attitude  ',
  'Anger  ',
];

// todo------------------------------> Family
List familyImage = [
  'assets/images/HomePage_Images/Family_Images/family.jpg',
  'assets/images/HomePage_Images/Family_Images/mom.jpg',
  'assets/images/HomePage_Images/Family_Images/dad.jpg',
  'assets/images/HomePage_Images/Family_Images/home.jpg',
  'assets/images/HomePage_Images/Family_Images/friends.jpg',
  'assets/images/HomePage_Images/Family_Images/parenting.jpg',
];

List familyText = [
  'Family  ',
  'Mom  ',
  'Dad  ',
  'Home  ',
  'Friends  ',
  'Parenting  ',
];

// todo------------------------------> Moments
List momentsImage = [
  'assets/images/HomePage_Images/Moments_Images/anniversary.jpg',
  'assets/images/HomePage_Images/Moments_Images/birthday.jpg',
  'assets/images/HomePage_Images/Moments_Images/dating.jpg',
  'assets/images/HomePage_Images/Moments_Images/wedding.jpg',
  'assets/images/HomePage_Images/Moments_Images/romantic.jpg',
  'assets/images/HomePage_Images/Moments_Images/death.jpg',
];

List momentsText = [
  'Anniversary  ',
  'Birthday  ',
  'Romantic  ',
  'Wedding  ',
  'Dating  ',
  'Death  ',
];

// todo------------------------------> Other
List otherImage = [
  'assets/images/HomePage_Images/Other/god.jpg',
  'assets/images/HomePage_Images/Other/age.jpg',
  'assets/images/HomePage_Images/Other/change.jpg',
  'assets/images/HomePage_Images/Other/communication.jpg',
  'assets/images/HomePage_Images/Other/env.jpg',
  'assets/images/HomePage_Images/Other/dreams.jpg',
];

List otherText = [
  'God  ',
  'Age  ',
  'Change  ',
  'Communication  ',
  'Environment  ',
  'Dreams  ',
];

List allPopularPageImages = [
   [
     'assets/images/CategoryWise_Images/LoveImages/l1.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l2.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l3.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l4.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l5.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l6.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l7.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l8.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l9.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/LifeImages/l1.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l2.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l3.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l4.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l5.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l6.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l7.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l8.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l9.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/MomImages/l1.jpg',
    'assets/images/CategoryWise_Images/MomImages/l2.jpg',
    'assets/images/CategoryWise_Images/MomImages/l3.jpg',
    'assets/images/CategoryWise_Images/MomImages/l4.jpg',
    'assets/images/CategoryWise_Images/MomImages/l5.jpg',
    'assets/images/CategoryWise_Images/MomImages/l6.jpg',
    'assets/images/CategoryWise_Images/MomImages/l7.jpg',
    'assets/images/CategoryWise_Images/MomImages/l8.jpg',
    'assets/images/CategoryWise_Images/MomImages/l9.jpg',
    'assets/images/CategoryWise_Images/MomImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/FriendshipImages/l1.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l2.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l3.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l4.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l5.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l6.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l7.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l8.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l9.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ]
];

List allMotivationPageImages = [
   [
     'assets/images/CategoryWise_Images/InspirationImages/l1.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l2.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l3.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l4.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l5.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l6.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l7.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l8.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l9.jpg',
     'assets/images/CategoryWise_Images/InspirationImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/CourageImages/l1.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l2.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l3.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l4.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l5.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l6.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l7.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l8.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l9.jpg',
    'assets/images/CategoryWise_Images/CourageImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/freedomImages/l1.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l2.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l3.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l4.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l5.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l6.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l7.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l8.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l9.jpg',
    'assets/images/CategoryWise_Images/freedomImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/IntelligenceImages/l1.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l2.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l3.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l4.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l5.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l6.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l7.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l8.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l9.jpg',
    'assets/images/CategoryWise_Images/IntelligenceImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/KnowledgeImages/l1.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l2.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l3.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l4.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l5.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l6.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l7.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l8.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l9.jpg',
    'assets/images/CategoryWise_Images/KnowledgeImages/l10.jpg',
  ]
];

List allFeelingsPageImages = [
   [
     'assets/images/CategoryWise_Images/AloneImages/l1.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l2.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l3.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l4.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l5.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l6.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l7.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l8.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l9.jpg',
     'assets/images/CategoryWise_Images/AloneImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/SadImages/l1.jpg',
    'assets/images/CategoryWise_Images/SadImages/l2.jpg',
    'assets/images/CategoryWise_Images/SadImages/l3.jpg',
    'assets/images/CategoryWise_Images/SadImages/l4.jpg',
    'assets/images/CategoryWise_Images/SadImages/l5.jpg',
    'assets/images/CategoryWise_Images/SadImages/l6.jpg',
    'assets/images/CategoryWise_Images/SadImages/l7.jpg',
    'assets/images/CategoryWise_Images/SadImages/l8.jpg',
    'assets/images/CategoryWise_Images/SadImages/l9.jpg',
    'assets/images/CategoryWise_Images/SadImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/TrustImages/l1.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l2.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l3.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l4.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l5.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l6.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l7.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l8.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l9.jpg',
    'assets/images/CategoryWise_Images/TrustImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/LifeImages/l1.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l2.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l3.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l4.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l5.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l6.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l7.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l8.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l9.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/AttitudeImages/l1.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l2.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l3.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l4.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l5.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l6.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l7.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l8.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l9.jpg',
    'assets/images/CategoryWise_Images/AttitudeImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/AngerImages/l1.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l2.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l3.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l4.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l5.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l6.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l7.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l8.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l9.jpg',
    'assets/images/CategoryWise_Images/AngerImages/l10.jpg',
  ]
];

List allFamilyPageImages = [
   [
     'assets/images/CategoryWise_Images/FamilyImages/l1.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l2.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l3.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l4.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l5.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l6.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l7.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l8.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l9.jpg',
     'assets/images/CategoryWise_Images/FamilyImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/MomImages/l1.jpg',
    'assets/images/CategoryWise_Images/MomImages/l2.jpg',
    'assets/images/CategoryWise_Images/MomImages/l3.jpg',
    'assets/images/CategoryWise_Images/MomImages/l4.jpg',
    'assets/images/CategoryWise_Images/MomImages/l5.jpg',
    'assets/images/CategoryWise_Images/MomImages/l6.jpg',
    'assets/images/CategoryWise_Images/MomImages/l7.jpg',
    'assets/images/CategoryWise_Images/MomImages/l8.jpg',
    'assets/images/CategoryWise_Images/MomImages/l9.jpg',
    'assets/images/CategoryWise_Images/MomImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/DadImages/l1.jpg',
    'assets/images/CategoryWise_Images/DadImages/l2.jpg',
    'assets/images/CategoryWise_Images/DadImages/l3.jpg',
    'assets/images/CategoryWise_Images/DadImages/l4.jpg',
    'assets/images/CategoryWise_Images/DadImages/l5.jpg',
    'assets/images/CategoryWise_Images/DadImages/l6.jpg',
    'assets/images/CategoryWise_Images/DadImages/l7.jpg',
    'assets/images/CategoryWise_Images/DadImages/l8.jpg',
    'assets/images/CategoryWise_Images/DadImages/l9.jpg',
    'assets/images/CategoryWise_Images/DadImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/HomeImages/l1.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l2.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l3.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l4.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l5.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l6.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l7.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l8.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l9.jpg',
    'assets/images/CategoryWise_Images/HomeImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/FriendshipImages/l1.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l2.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l3.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l4.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l5.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l6.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l7.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l8.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l9.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ]
];

List allMomentsPageImages = [
   [
     'assets/images/CategoryWise_Images/AnniversaryImages/l1.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l2.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l3.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l4.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l5.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l6.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l7.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l8.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l9.jpg',
     'assets/images/CategoryWise_Images/AnniversaryImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/BirthdayImages/l1.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l2.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l3.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l4.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l5.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l6.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l7.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l8.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l9.jpg',
    'assets/images/CategoryWise_Images/BirthdayImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/MomImages/l1.jpg',
    'assets/images/CategoryWise_Images/MomImages/l2.jpg',
    'assets/images/CategoryWise_Images/MomImages/l3.jpg',
    'assets/images/CategoryWise_Images/MomImages/l4.jpg',
    'assets/images/CategoryWise_Images/MomImages/l5.jpg',
    'assets/images/CategoryWise_Images/MomImages/l6.jpg',
    'assets/images/CategoryWise_Images/MomImages/l7.jpg',
    'assets/images/CategoryWise_Images/MomImages/l8.jpg',
    'assets/images/CategoryWise_Images/MomImages/l9.jpg',
    'assets/images/CategoryWise_Images/MomImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ]
];

List allOtherPageImages = [
   [
     'assets/images/CategoryWise_Images/LoveImages/l1.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l2.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l3.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l4.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l5.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l6.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l7.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l8.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l9.jpg',
     'assets/images/CategoryWise_Images/LoveImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/LifeImages/l1.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l2.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l3.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l4.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l5.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l6.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l7.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l8.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l9.jpg',
    'assets/images/CategoryWise_Images/LifeImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/WorkImages/l1.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l2.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l3.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l4.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l5.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l6.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l7.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l8.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l9.jpg',
    'assets/images/CategoryWise_Images/WorkImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/MomImages/l1.jpg',
    'assets/images/CategoryWise_Images/MomImages/l2.jpg',
    'assets/images/CategoryWise_Images/MomImages/l3.jpg',
    'assets/images/CategoryWise_Images/MomImages/l4.jpg',
    'assets/images/CategoryWise_Images/MomImages/l5.jpg',
    'assets/images/CategoryWise_Images/MomImages/l6.jpg',
    'assets/images/CategoryWise_Images/MomImages/l7.jpg',
    'assets/images/CategoryWise_Images/MomImages/l8.jpg',
    'assets/images/CategoryWise_Images/MomImages/l9.jpg',
    'assets/images/CategoryWise_Images/MomImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/FriendshipImages/l1.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l2.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l3.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l4.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l5.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l6.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l7.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l8.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l9.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l10.jpg',
  ],
  [
    'assets/images/CategoryWise_Images/FriendshipImages/l1.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l2.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l3.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l4.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l5.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l6.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l7.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l8.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l9.jpg',
    'assets/images/CategoryWise_Images/FriendshipImages/l10.jpg',
  ],
];

List showImages = [];

Text headingOfHomepage(double width, String data) {
  return Text(
    data,
    style: TextStyle(
        color: Colors.white, fontFamily: 'gc_m', fontSize: width * 0.0545),
  );
}
